### ISSUE TITLE
potential bug: pmdg 737 autopilot kicks off on autoland 

### ISSUE THREAD

**Issue by blindflightsimmer** [Sequal32/yourcontrols#215]
Hi. I am a blind pilot, we use screenreaders ETC to fly, great addon have had a lot of fun using it. Seems to be however that, on an autoland, which we do often as blind pilots for rather obvious reasons, one of the users, usually the one not hosting, gets their A/P kicked out as you approach the runway. This is of course with both cmd A and B engaged after capturing the ILS. This does not seem to happen all of the time and am trying to find exact cause, but some logic to prevent this would be great.

**Comment by rthom91** [comment]
Sounds like someone might have a yoke sending AP toggle on/off commands.

The only other way would be shooting a specific event through simconnect which would mean someone is pressing a button pre-configured to disconnect AP. This would be possible if someone is running another app such as FSUIPC, Mobiflight, or Spad.next. However, this would affect both of you. But since it is only happening to one person I feel this is an issue with a yoke. Check your sim bindings because you may have buggy autopilot switch starting to go bad. I have seen this happen with a honeycomb alpha by banging on the top of it.
